# Generated by Django 4.2.15 on 2024-08-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(max_length=150)),
                ('term', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=150)),
                ('market_phone_number', models.IntegerField()),
                ('market_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Online Market',
                'verbose_name_plural': 'Online Market',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_category', to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_price', models.IntegerField()),
                ('product_description', models.TextField()),
                ('discount', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_discount', to='myapp.discount')),
                ('sub_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_sub_category', to='myapp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('product', models.ManyToManyField(blank=True, to='myapp.products')),
                ('product_attribute', models.ManyToManyField(blank=True, related_name='product_attribute', to='myapp.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_product', to='myapp.products')),
            ],
        ),
    ]
