# Generated by Django 4.2.15 on 2024-08-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_basket_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(to='myapp.products'),
        ),
    ]
